# Generated by Django 4.2 on 2023-05-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.CharField(max_length=250),
        ),
    ]
